services:
  postgres:
    image: postgres:17
    container_name: siact_db
    restart: on-failure
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: siact
      POSTGRES_PASSWORD: siact
      POSTGRES_DB: siact
    volumes:
      - pgdata:/var/lib/postgresql/data

    

volumes:
  pgdata:
